# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 098ca6a529609099de19d44f4dd5d2db1e055ebeb69cbfe9249e3b9ba648b95799c44a0439df8da7b425207cf5168e3570468de7020877bfd43b0bf8d32337b8

test:
  secret_key_base: c34cef8ba3e7b3c13fef8d2fd1df8cf7088417f35aa6111dc7ccafc8c16fda32d0e7c5f7f0640754e5c2d36ea6324b5fd080c35e4bc882113269b722ae6d968e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
